### ISSUE TITLE
E688 on startup with neovim

### ISSUE THREAD

**Issue by sethwoodworth** [dahu/vimple#11]
Like in issue #4, I get the E688 error on startup while using the commentary plugin but for the version.vim

```
Error detected while processing function vimple#version#new..48:
line    4:
E688: More targets than List items
Press ENTER or type command to continue
```

I don't see anything obviously weird in version.vim. but I don't know how the line numbers in vim exceptions work.

**Comment by sethwoodworth** [comment]
Let me know if you don't mean to support Neovim.  I'm ultimately trying to use your vim-asciidoc plugin.

**Comment by dahu** [comment]
I have not looked at why you are getting this error yet, but you can disable all of the vimple objects by putting this line in your ~/.vimrc:

  let vimple_init_vars = 0

or you can disable just the version object:

  let vimple_init_vn = 0

vim-asciidoc does not depend on any of the vimple objects -- it uses the vimple library code.

To fix the problem, I'm going to need to see your   :version   output. I bet this is because neovim has changed the version structure. As a general note, I have not tried neovim and therefore I have not tested any of my plugins on neovim.

**Comment by sethwoodworth** [comment]
[https://gist.github.com/e74e31330b93d02bdece](:version gist)  

`let vimple_init_vars = 0` works to squash the warning. 

Also feel free to say you aren't supporting neovim ATM.

**Comment by dahu** [comment]
I certainly am not (yet) supporting neovim. Looking at your version string,
neovim structures things quite differently.

**Comment by sethwoodworth** [comment]
`let vimple_init_vn = 0` instead of `vimple_init_vars` lets me use vimple successfully.

**Comment by dahu** [comment]
Good to know.
